### ISSUE TITLE
index_type ptr_diff

### ISSUE THREAD

**Issue by stayprivates** [martinmoene/span-lite#21]
I glanced at p0122r6.pdf and could not find an answer.  size() returns a type index_type which is a ptrdiff_t. 
ptrdiff_t is signed, so for code that does something similar to:

if ( std::vector::size() != std::span::size() )

I will get a compiler warning about comparing signed and unsigned. I do not understand why a span size could be negative. 

What is the rational for using ptrdiff_t here?  Given that some of span's constructor can accept size_t that means one could create a span with a size bigger than what span::size() could actually return ?

I understand this has nothing to do with your implementation but was wondering if you had any comment about this.  I assume usage of ptrdiff_t is required by math is performed on pointers?

**Comment by martinmoene** [comment]
The historical choice of using an unsigned type for indices is regretted by some/many people working on/with C++. Changing to signed type is considered controversial by some/many working on/with C++.

Several references I could find:

- [p0122, latest: span: bounds safe views for sequences of objects ](http://wg21.link/p0122), page 7:

>The type used for measuring and indexing into span is ptrdiff_t. Using a signed index type helps avoid common mistakes that come from implicit signed to unsigned integer conversions when users employ integer literals (which are nearly always signed). The use of ptrdiff_t is natural as it is the type used for pointer arithmetic and array indexing – two operations that span explicitly aims to replace but that an implementation of span would likely rely upon. 

- [p1089 - Sizes Should Only span Unsigned](http://wg21.link/p1089).

- [M-GSL issue 339: span index is an int instead of unsigned int ](https://github.com/Microsoft/GSL/issues/339).

- [M-GSL issue 322: size of span, signed versus unsigned](https://github.com/Microsoft/GSL/issues/322).

- [M-GSL issue 264: size() should be size_t](https://github.com/Microsoft/GSL/issues/264).

- [M-GSL issue 238: What is the rationnal for using signed integer as size ?](https://github.com/Microsoft/GSL/issues/238).

- [M-GSL issue 171: size_type should be unsigned](https://github.com/Microsoft/GSL/issues/171).

**Comment by grandseiken** [comment]
@martinmoene https://www.reddit.com/r/cpp/comments/9vwvbz/2018_san_diego_iso_c_committee_trip_report_ranges/ reports that `size()` will be `size_t` in C++20 (i.e. p1089r2 got accepted). Is that enough to make the change in this library?

**Comment by martinmoene** [comment]
@grandseiken Thanks!

The idea is to follow the (evolving) standard, so I'll revisit the code in light of what will/has become of C++20. 

---

NTS: perhaps provide a configuration macro for backwards compatibility.

**Comment by martinmoene** [comment]
Plan:
- [ ] Add `typedef std::ptrdiff_t extent_t;`
- [ ] Change `index_t Extent` to `extent_t Extent`
- [ ] Add configuration macro `span_CONFIG_INDEX_TYPE  std::size_t`
- [ ] Update Readme
- [ ] ....

**Comment by ululi1970** [comment]
I think this is related to this issue
When compiling code containing nonstd::span with the CUDA compiler( nvcc), I get a 
'Warning: integer conversion resulted in a change of sign" at lines 722, 737 and 754. 
The lines that trigger the warning are all the same

(Extent == dynamic_extent || Extent == N)

Here, Extent and dynamic_extent are of type std::ptrdiff_t, whereas N is site_t. 
Upcasting N to std::ptrdiff_t takes care of the warning, but I just wanted to make sure that it does not 
break the intended behavior...

**Comment by ululi1970** [comment]
Thanks to you for sharing this nice implementation of span.
